#### Taxonomy {#taxonomy}

```{r remove}

  regexRemove <- c("quotation marks", "question marks", "trailing 'spp.' or 'sp.'", "leading space", "trailing space")

```

Taxa were queried against the taxonomic backbone used by the Atlas of Living Australia (ALA; https://support.ala.org.au/support/solutions/articles/6000261677-taxonomy-in-the-ala) using the `make_taxonomy` function in the `envClean` package `r cite_package("envClean")`, which uses the ALA's `galah` package `r cite_package("galah")`. This taxonomic backbone is built from a number of taxonomy authorities such as the National Species List, Australian Plant Census, and Australian Faunal Directory. The resulting taxonomy lookup table was joined to the occurrence data to provide an aligned taxonomic names.

Prior to querying against ALA the following cleaning steps were undertaken:

-   any record of a taxon that contained any of the following text in its name (ignoring case) was removed:
    -   `r paste0(settings$species_filt, collapse = "\n    + ")`
-   any of the following regular expressions in a taxon name were removed from the name (via `gsub`):
    -   `r paste0(regexRemove, collapse = "\n    + ")`
-   any text including and after ' x ' or ' X ', in a taxon name, was removed from the name (thus any hybrids were most likely assigned to the first taxon recorded within the hybrid)

The taxa used in analyses were always binomial (taxa recorded at taxonomic level below species were binned at species level (e.g. *Acanthiza iredalei rosinae* was attributed to *Acanthiza iredalei*). Any record that could not be matched to a name at `r settings$analysis_rank` level, or better, was removed. 

Occasionally duplicate accepted taxon names exist within the ALA taxonomy for the same entity due to taxonomic updates that are in progress, unresolved taxonomies, or recording errors (e.g. recording an international related species instead of the Australian species). Where duplicate accepted taxon names were identified, these were manually combined to the most recently accepted binomial.  For example, the Brolga is accepted in ALA as both *Grus rubicunda* and *Antigone rubicunda*. Both genera have been used in the past, and the original but then superseded *Antigone* has recently been revived following DNA analysis. To avoid Brolga records being separated and treated as two separate species, when in reality all records come from only one species, a manual fix was added to assign both binomials to the more recently-accepted *Antigone rubicunda*. Similarly, the ALA taxonomic backbone would rarely return an incorrect taxon name. When identified, manual fixes were also applied to these taxa.

See Appendix [Taxonomy][Manual fixes & overrides] for a list of these `taxonomy_overrides` that are generated by `envStatus` and from `taxonomy_overrides` in `envClean`, and all `original_names` that were aligned to each ALA binomial by `make_taxonomy` from `envClean`. 

`r paste0(clean_text$text[i], " ", clean_text$context_text[i])`


