---
title: "Species Risk Assessment"
subtitle: "A short guide"
author:
- Department for Environment and Water
output:
  bookdown::gitbook:
    split_bib: false
    toc_depth: 3
    fig_caption: true
    reference_docx: "Styles.docx"
link-citations: yes
always_allow_html: yes
csl: "bib_style.csl"
bibliography:
- "all_refs.bib"
---

```{r tars, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}

library(targets)

# these tars only work inside a knit (otherwise use _targets.yaml directly)
tars <- yaml::read_yaml(here::here("_targets.yaml")) |>
  purrr::modify_tree(leaf = \(x) gsub("\\.\\.\\/\\.\\.", "../../..", x))

```

```{r setup, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}

# # load targets -------
tar_load_everything(store = tars$report_prep$store)
tar_load_everything(store = tars$envBird$database$store)
tar_load_everything(store = tars$envBird$birdcoin$store)
tar_load_everything(store = tars$birdraster$store)

#--------knitr options--------

knitr::opts_chunk$set(echo = FALSE
                      , warning = FALSE
                      , error = FALSE
                      , message = FALSE
                      , tidy = TRUE
                      , tidy.opts = list(comment = FALSE)
                      , eval.after = "fig.cap" 
                      , output_dir = here::here("report")
                      , progress = FALSE
                      # , dpi = 150
                      , fig.width = 6.5
)

#--------book options-------

options(
  knitr.kable.NA = "",
  knitr.duplicate.label = "allow"
)

# --- tmap options ---

# view/plot mode
#depending on output format
is_html_output <-  function() {
  knitr::opts_knit$get("rmarkdown.pandoc.to")=="html"
}

if(is_html_output()) {
  use_tmap_mode <- "view"
} else {
  use_tmap_mode <- "plot"
  knitr::opts_chunk$set(fig.width = 6.5)
}

##or set manually
if(FALSE){use_tmap_mode <- "plot"}

tmap::tmap_mode(use_tmap_mode)

#suppress progress bars
terra::terraOptions(progress=0)

```

# Aim {-}

To systematically assess species vulnerability to solar and wind farm development in the Upper Spencer Gulf–Gawler Ranges and Braemar Province pilot area.

